name: Create Release Tarball

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tarball
        run: |
          mkdir release
          cp -r bash_completion.sh zsh_completion.sh LICENSE README.md release/
          tar -czvf openqa-client-completion-${{ github.ref_name }}.tar.gz -C release .
      
      - name: Upload tarball
        uses: actions/upload-release-asset@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: ./openqa-client-completion-${{ github.ref_name }}.tar.gz
          asset_name: openqa-client-completion-${{ github.ref_name }}.tar.gz
          content_type: application/gzip
